export const ACTION_TYPES = {
    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    FETCH_ALL_EMPLOYEE: 'FETCH_ALL_EMPLOYEE',
    CREATE_PHONE: 'CREATE_PHONE',
    UPDATE_PHONE: 'UPDATE_PHONE',
    DELETE_PHONE: 'DELETE_PHONE',
    FETCH_ALL_PHONE: 'FETCH_ALL_PHONE',
    CREATE_PROJECT: 'CREATE_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    FETCH_ALL_PROJECT: 'FETCH_ALL_PROJECT',
    FETCH_BY_ID_PROJECT: 'FETCH_BY_ID_PROJECT',
    ADD_EMPLOYE_PROJECT: "ADD_EMPLOYE_PROJECT",
    DELETE_EMPLOYE_PROJECT: "DELETE_EMPLOYE_PROJECT",
    FETCH_ALL_EMPLOYEE_IDS: "FETCH_ALL_EMPLOYEE_IDS"
}